class ConfigJogo:
    LARGURA_TELA = 600
    ALTURA_TELA = 400
    COR_ESTADO = (0, 0, 255)
    COR_TITULO = (0, 0, 0)
    ALTURA_PLACAR = 0.1 * ALTURA_TELA
    ALTURA_TEMPO = 0.15 * ALTURA_TELA
    DURACAO_PARTIDA = 60
    FONTE_TITULO = 72
    FONTE_SUBTITULO = 36